baseURL = "https://wenmeiyu.github.io/"
theme = "hugo-goa"
author = "Wenmeiyu"
title = "Wenmeiyu Blog"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"



[params]
author = "Wenmeiyu"
intro = "You can do it as long as you think!"
description = "Description"
authorimage = "mg.jpg"
dateformat = "Jan 2, 2006"

[[menu.main]]
    name = "blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "program"
    weight = 200
    url = "/program/"
[[menu.main]]
    name = "study"
    weight = 300
    url = "/study/"


[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

[params.social]
github = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
stackoverflow = "<username>"
email = "you@example.com"

[params.extra]
copyright = "copyright @ Rajesh Shenoy"
poweredby = true
highlightjs = true


	
